### ISSUE TITLE
brick无法启动

### ISSUE THREAD

**Issue by yutong-it** [httaotao/glusterfs-book#2]
我们有15台左右的服务器，在某一时刻，2台glusterd进程启动后，brick无法拉起来，24007端口也不通，tcp的backlog调大了也不行，端口还是不通，但是端口已经监听了，是不是volume过多导致，目前有500多个volume，平均每台服务器有150个brick，有没有遇到这样的问题？

**Comment by httaotao** [comment]
你这样说看不懂，建议去glusterfs 那里提问，带上具体的排查日志信息。
