### ISSUE TITLE
少了一章3.4.4

### ISSUE THREAD

**Issue by WinterTwenty** [httaotao/glusterfs-book#5]

**Comment by httaotao** [comment]
gitlab可以下载完整版的，那里有




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "httaotao/glusterfs-book"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月12日(星期二) 下午5:21
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[httaotao/glusterfs-book] 少了一章3.4.4 (Issue #5)

**Comment by WinterTwenty** [comment]
感谢！
